# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Udelta блог
subtitle: Интернет-маркетинг
description:
author: Udelta
language: ru
timezone: Europe/Moscow

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.udelta.ru
cdn: https://s-blog.udelta.ru
root: /
permalink: :year/:month/:title/
permalink_defaults:
authors_link: /authors/


# Directory
source_dir: source
public_dir: public_html
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

feed:
  type: atom
  path: rss.xml
  limit: 20
  hub:
  content:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

plugins:


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


# Оптимизация

hfc_useref:
  enable: true
  concat: true
  exclude:

hfc_html:
  enable: true
  removeComments: true
  removeCommentsFromCDATA: true
  collapseWhitespace: true
  collapseBooleanAttributes: true
  removeEmptyAttributes: true
  minifyJS: true
  minifyCSS: true
  exclude:

hfc_css:
  enable: true
  exclude: 
    - '*.min.css'

hfc_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

hfc_img:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 4
  pngquant: true
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: true
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: true

hfc_favicons:
  enable: false
  src: image/logo.png
  target: img/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false

uncss:
  enable   : false
  ignore   : "#added_at_runtime"
  media    : ['(min-width: 700px) handheld and (orientation: landscape)']
  priority : 10
  timeout  : 3000

criticalcss:
  enable: true
  critical:
    minify: true

sitemap:
    path: sitemap.xml

robotstxt:
  useragent: "*"
  disallow:
  allow:
  sitemap: /sitemap.xml